bucket          = "stg-dlk-cicd-tf-states"
key             = "ds100/sbx/terraform.tfstate"
region          = "eu-west-1"
dynamodb_table  = "stg-dlk-cicd-tfstate-lock"
role_arn        = "arn:aws:iam::816247855850:role/stg-dlk-devops"

